### 프로그래머스 7day SQL 챌린지 ###
# url: https://programmers.co.kr/events/7day-sql?utm_source=mailchimp&utm_medium=post_7daySQL&utm_campaign=7daySQL

# 1일차
SELECT * from ANIMAL_INS order by ANIMAL_ID asc
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC

# 2일차
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = 'Sick';
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION != 'Aged' ORDER BY ANIMAL_ID ASC;

# 3일차
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME is NULL ORDER BY ANIMAL_ID ASC
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME ASC LIMIT 1;
SELECT MIN(DATETIME) FROM ANIMAL_INS GROUP BY ANIMAL_TYPE;
